language: java

jdk:
  - oraclejdk8

before_install:
 - chmod +x gradlew
 - export GRADLE_USER_HOME=$HOME/.cache/.gradle

notifications:
  email: false
  
script:
 - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
 - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
 - ./gradlew clean build upload

install:
- true

cache:
  directories:
   - .autoconf
   - $HOME/.cache/.gradle
   - $HOME/.m2

