package cn.academy;

import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.item.Item;
import net.minecraft.item.ItemBlock;
import net.minecraft.client.renderer.block.model.ModelResourceLoader;

import net.minecraftforge.fml.common;
import net.minecraftforge.fml.relauncher.SideOnly;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.client.model.ModelLoader;

import cn.lambdalib2.registry.StateEventCallback;

/**
 * Automatically generated by LambdaLib2.xconf in 2018-08-15 19:36:13.
 */
public class ACBlocks {

    public static final cn.academy.block.block.BlockGenericOre constraint_metal = new cn.academy.block.block.BlockGenericOre(4.0f, 1);

    public static final ItemBlock item_constraint_metal = new ItemBlock(constraint_metal);

    @RegistryCallback
    private static void registerBlocks(RegistryEvent.Register<Block> event) {
        constraint_metal.setRegistryName("ac_constraint_metal");
        constraint_metal.setUnlocalizedName("academy:constraint_metal");
        event.getRegistry().register(constraint_metal);
    }

    @RegistryCallback
    private static void registerItems(RegistryEvent.Register<Item> event) {
        item_constraint_metal.setRegistryName("academy:constraint_metal");
        item_constraint_metal.setUnlocalizedName("academy:constraint_metal");
        event.getRegistry().register(item_constraint_metal);

        if (FMLCommonHandler.INSTANCE.getSide() == Side.CLIENT) {
            registerItemRenderers();
        }
    }

    @SideOnly(Side.CLIENT)
    private static void registerItemRenderers() {
        ModelLoader.setCustomModelResourceLocation(item_constraint_metal, 0, new ModelResourceLocation(constraint_metal.getRegistryName(), "inventory"));
    }

}