package cn.academy;

import cn.lambdalib2.registry.RegistryCallback;
import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.item.Item;
import net.minecraft.client.renderer.block.model.ModelResourceLoader;

import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.relauncher.SideOnly;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.client.model.ModelLoader;

import cn.lambdalib2.registry.StateEventCallback;

/**
 * Automatically generated by LambdaLib2.xconf in 2018-08-15 19:36:13.
 */
public class ACItems {

    public static final net.minecraft.item.Item brain_component = new net.minecraft.item.Item();

    @RegistryCallback
    private static void registerItems(RegistryEvent.Register<Item> event) {
        brain_component.setRegistryName("ac_brain_component");
        brain_component.setUnlocalizedName("academy:brain_component");
        event.getRegistry().register(brain_component);

        if (FMLCommonHandler.INSTANCE.getSide() == Side.CLIENT) {
            registerItemRenderers();
        }
    }

    @SideOnly(Side.CLIENT)
    private static void registerItemRenderers() {
        ModelLoader.setCustomModelResourceLocation(brain_component, 0, new ModelResourceLocation(brain_component.getRegistryName(), "inventory"));
    }

}