/**
 * Copyright (c) Lambda Innovation, 2013-2015
 * 本作品版权由Lambda Innovation所有。
 * http://www.li-dev.cn/
 *
 * This project is open-source, and it is distributed under
 * the terms of GNU General Public License. You can modify
 * and distribute freely as long as you follow the license.
 * 本项目是一个开源项目，且遵循GNU通用公共授权协议。
 * 在遵照该协议的情况下，您可以自由传播和修改。
 * http://www.gnu.org/licenses/gpl.html
 */
package cn.academy.core.block;

import cn.academy.core.tile.TileInventory;
import cn.academy.energy.api.block.IWirelessGenerator;
import cn.annoreg.core.Registrant;
import cn.annoreg.mc.network.RegNetworkCall;
import cn.annoreg.mc.s11n.StorageOption;
import cn.annoreg.mc.s11n.StorageOption.Data;
import cpw.mods.fml.relauncher.Side;

/**
 * @author WeAthFolD
 */
@Registrant
public abstract class TileGeneratorBase extends TileInventory implements IWirelessGenerator {
	
	final double bufferSize;
	final double bandwidth;
	
	private int updateTicker = 20;
	
	/**
	 * Amount of buffered energy.
	 */
	private double energy;

	public TileGeneratorBase(String _invName, int size, double _bufferSize, double _bandwidth) {
		super(_invName, size);
		bufferSize = _bufferSize;
		bandwidth = _bandwidth;
	}
	
	@Override
	public void updateEntity() {
		if(!getWorldObj().isRemote) {
			double required = bufferSize - energy;
			if(required > 0) {
				energy += getGeneration(required);
			}
			if (energy > bufferSize)
				energy = bufferSize;
			
			if(--updateTicker == 0) {
				updateTicker = 20;
				syncToClient(energy);
			}
		}
	}

	@Override
	public double getProvidedEnergy(double req) {
		if(energy > req) req = energy;
		
		energy -= req;
		return req;
	}

	@Override
	public double getBandwidth() {
		return bandwidth;
	}
	
	/**
	 * Get the energy generated by the generator this tick.
	 */
	public abstract double getGeneration(double required);
	
	@RegNetworkCall(side = Side.CLIENT, thisStorage = StorageOption.Option.INSTANCE)
	private void syncToClient(@Data Double energy) {
		this.energy = energy;
	}

}
