package cn.academy.api.ctrl;

/**
 * Event Type ID sent to a skill class.
 * Now only contains raw events. Skills never receive these events.
 * @author acaly
 *
 */
public enum SkillEventType {
	
	/**
	 * When a key is pressed.
	 */
	RAW_DOWN,
	
	/**
	 * When a key is released.
	 */
	RAW_UP,
	
	/**
	 * Client side periodically sends KEY_PRESS to server.
	 * This event is only sent from EventHandlerClient to EventHandlerServer.
	 */
	RAW_CLIENT_DOWN,
	
	/**
	 * Client send a RAW_CLIENT_UP event to server when a double click failed.
	 * This event is only sent from EventHandlerClient to EventHandlerServer.
	 */
	RAW_CLIENT_UP,
	
	/**
	 * Tick in both sides when pressing.
	 * Generated by EventHandler (SingleSkill) which sends it to patterns.
	 */
	RAW_TICK_DOWN,
	
	/**
	 * Tick in both sides after key up but before finish click.
	 * Generated by EventHandler (SingleSkill) which sends it to patterns.
	 */
	RAW_TICK_UP,

	/**
	 * Server send RAW_CANCEL to client when there's an error,
	 * typically caused by increasing network latency.
	 */
	RAW_CANCEL,
	
	/**
	 * RawEventHandler receive RAW_TICK every tick when needed.
	 */
	RAW_TICK,
	
	/**
	 * When a key is double clicked.
	 * Generated by EventHandler on both sides.
	 */
	RAW_DBLCLK,
	
	/**
	 * When a double click failed.
	 * Will have small delay compared with KEY_UP.
	 * Generated by EventHandler on both sides.
	 */
	RAW_CLICK,
	
	/**
	 * Adjust server skill time when RAW_UP.
	 * Patterns should determine hold event with this event.
	 */
	RAW_ADJUST,
	
}
