package cn.academy.api.ctrl;

/**
 * Event Type ID sent to a skill class.
 * @author acaly
 *
 */
public enum SkillEventType {
	
	/**
	 * When a key is pressed. 
	 * Raw Event. Don't use it in skill class directly.
	 */
	RAW_DOWN,
	
	/**
	 * When a key is released.
	 * Raw Event. Don't use it in skill class directly.
	 */
	RAW_UP,
	
	/**
	 * Client side periodically sends KEY_PRESS to server.
	 * This event is only used between event handlers.
	 * Raw Event. Don't use it in skill class directly.
	 */
	RAW_CLIENT_DOWN,
	
	/**
	 * Client send a RAW_CLIENT_UP event to server when a double click failed.
	 * This event is only used between event handlers.
	 * Raw Event. Don't use it in skill class directly.
	 */
	RAW_CLIENT_UP,
	
	/**
	 * Tick in both sides when pressing.
	 * Generated by EventHandler (SingleSkill).
	 * Raw Event. Don't use it in skill class directly.
	 */
	RAW_TICK_DOWN,
	
	/**
	 * Tick in both sides after key up but before finish click.
	 */
	RAW_TICK_UP,

	/**
	 * Server send RAW_CANCEL to client when there's an error,
	 * typically caused by increasing network latency.
	 */
	RAW_CANCEL,
	
	/**
	 * RawEventHandler receive RAW_TICK every tick when needed
	 */
	RAW_TICK,
	
	/**
	 * When a key is double clicked.
	 */
	RAW_DBLCLK,
	
	/**
	 * When a double click failed.
	 * Will have small delay compared with KEY_UP.
	 */
	RAW_CLICK,
	
	/**
	 * Adjust server skill time when RAW_UP.
	 * Determine hold event with this event.
	 */
	RAW_ADJUST,
	
	/**
	 * Start of a skill. 
	 * Usually right after KEY_DOWN.
	 */
	SKILL_START,
	
	/**
	 * End of a skill.
	 * Usually after KEY_UP, but may also have a delay.
	 */
	SKILL_END,
	
	/**
	 * When the player keeps pressing a key for some time (time provided by skill).
	 */
	KEY_TIMER_TRIGGERED,
	
}
